import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const catalogs = {
  en: { welcome: 'Welcome back', register: 'Create account', overview: 'Overview', transactions: 'Transactions', settings: 'Settings', workspace: 'Workspace', profile: 'Profile', save: 'Save preferences', currency: 'Currency', language: 'Language', preferencesSaved: 'Preferences saved.', logout: 'Log out', userControl: 'User control', yourKhata: 'Your khata', fullName: 'Full name', username: 'Username', email: 'Email', newPassword: 'New password', updateProfile: 'Update profile', demoNotice: 'Demo accounts can update currency only.', profileSubtitle: 'Personalise your account and money display.', newEntry: 'New entry', addTransaction: 'Add transaction', cashIn: 'Cash in', cashOut: 'Cash out', category: 'Category', personBusiness: 'Person / business', note: 'Note', saveTransaction: 'Save transaction', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in...', createAccount: 'Create account', creatingAccount: 'Creating account...', confirmPassword: 'Confirm password', preferredCurrency: 'Preferred currency', alreadyAccount: 'Already have an account?', newToKhata: 'New to Khata?', signInLink: 'Sign in', createAccountLink: 'Create an account', goodToSeeYou: 'Good to see you.', loginSubtitle: 'Keep your money conversations clear and your records close.' },
  ur: { welcome: 'خوش آمدید', register: 'اکاؤنٹ بنائیں', overview: 'جائزہ', transactions: 'لین دین', settings: 'ترتیبات', workspace: 'ورک اسپیس', profile: 'پروفائل', save: 'ترجیحات محفوظ کریں', currency: 'کرنسی', language: 'زبان', preferencesSaved: 'ترجیحات محفوظ ہو گئیں۔', logout: 'لاگ آؤٹ', userControl: 'صارف کنٹرول', yourKhata: 'آپ کا کھاتہ', fullName: 'پورا نام', username: 'صارف نام', email: 'ای میل', newPassword: 'نیا پاس ورڈ', updateProfile: 'پروفائل اپ ڈیٹ کریں', demoNotice: 'ڈیمو اکاؤنٹس صرف کرنسی تبدیل کر سکتے ہیں۔', profileSubtitle: 'اپنے اکاؤنٹ اور رقم کی نمائش کو ذاتی بنائیں۔', newEntry: 'نئی اندراج', addTransaction: 'لین دین شامل کریں', cashIn: 'آمدنی', cashOut: 'خرچ', category: 'زمرہ', personBusiness: 'شخص / کاروبار', note: 'نوٹ', saveTransaction: 'لین دین محفوظ کریں', password: 'پاس ورڈ', signIn: 'سائن اِن', signingIn: 'سائن اِن ہو رہا ہے...', createAccount: 'اکاؤنٹ بنائیں', creatingAccount: 'اکاؤنٹ بنایا جا رہا ہے...', confirmPassword: 'پاس ورڈ کی تصدیق', preferredCurrency: 'پسندیدہ کرنسی', alreadyAccount: 'پہلے سے اکاؤنٹ ہے؟', newToKhata: 'کھاتا پر نئے ہیں؟', signInLink: 'سائن اِن', createAccountLink: 'اکاؤنٹ بنائیں', goodToSeeYou: 'آپ کو دیکھ کر خوشی ہوئی۔', loginSubtitle: 'اپنے مالی معاملات کو واضح رکھیں اور اپنے ریکارڈ محفوظ رکھیں۔' },
  hi: { welcome: 'वापसी पर स्वागत है', register: 'खाता बनाएं', overview: 'अवलोकन', transactions: 'लेन-देन', settings: 'सेटिंग्स', workspace: 'कार्यस्थान', profile: 'प्रोफ़ाइल', save: 'प्राथमिकताएं सहेजें', currency: 'मुद्रा', language: 'भाषा', preferencesSaved: 'प्राथमिकताएं सहेजी गईं।', logout: 'लॉग आउट', yourKhata: 'आपका खाता', fullName: 'पूरा नाम', username: 'उपयोगकर्ता नाम', email: 'ईमेल', newPassword: 'नया पासवर्ड', updateProfile: 'प्रोफ़ाइल अपडेट करें', demoNotice: 'डेमो खाते केवल मुद्रा बदल सकते हैं।', profileSubtitle: 'अपने खाते और पैसे के प्रदर्शन को अनुकूलित करें।', newEntry: 'नई प्रविष्टि', addTransaction: 'लेन-देन जोड़ें', cashIn: 'आमदनी', cashOut: 'खर्च', category: 'श्रेणी', personBusiness: 'व्यक्ति / व्यवसाय', note: 'नोट', saveTransaction: 'लेन-देन सहेजें' },
  ar: { welcome: 'مرحباً بعودتك', register: 'إنشاء حساب', overview: 'نظرة عامة', transactions: 'المعاملات', settings: 'الإعدادات', workspace: 'مساحة العمل', profile: 'الملف الشخصي', save: 'حفظ التفضيلات', currency: 'العملة', language: 'اللغة', preferencesSaved: 'تم حفظ التفضيلات.', logout: 'تسجيل الخروج', yourKhata: 'دفترك', fullName: 'الاسم الكامل', username: 'اسم المستخدم', email: 'البريد الإلكتروني', newPassword: 'كلمة المرور الجديدة', updateProfile: 'تحديث الملف الشخصي', demoNotice: 'يمكن للحسابات التجريبية تحديث العملة فقط.', profileSubtitle: 'خصص حسابك وطريقة عرض أموالك.', newEntry: 'إدخال جديد', addTransaction: 'إضافة معاملة', cashIn: 'دخل', cashOut: 'مصروف', category: 'الفئة', personBusiness: 'الشخص / الشركة', note: 'ملاحظة', saveTransaction: 'حفظ المعاملة' },
  es: { welcome: 'Bienvenido de nuevo', register: 'Crear cuenta', overview: 'Resumen', transactions: 'Transacciones', settings: 'Configuración', workspace: 'Espacio de trabajo', profile: 'Perfil', save: 'Guardar preferencias', currency: 'Moneda', language: 'Idioma', preferencesSaved: 'Preferencias guardadas.', logout: 'Cerrar sesión', yourKhata: 'Tu khata', fullName: 'Nombre completo', username: 'Nombre de usuario', email: 'Correo electrónico', newPassword: 'Nueva contraseña', updateProfile: 'Actualizar perfil', demoNotice: 'Las cuentas demo solo pueden actualizar la moneda.', profileSubtitle: 'Personaliza tu cuenta y la vista de tu dinero.', newEntry: 'Nueva entrada', addTransaction: 'Añadir transacción', cashIn: 'Ingreso', cashOut: 'Gasto', category: 'Categoría', personBusiness: 'Persona / negocio', note: 'Nota', saveTransaction: 'Guardar transacción' },
  fr: { welcome: 'Bon retour', register: 'Créer un compte', overview: 'Vue d’ensemble', transactions: 'Transactions', settings: 'Paramètres', workspace: 'Espace de travail', profile: 'Profil', save: 'Enregistrer', currency: 'Devise', language: 'Langue', preferencesSaved: 'Préférences enregistrées.', logout: 'Se déconnecter', yourKhata: 'Votre khata', fullName: 'Nom complet', username: 'Nom d’utilisateur', email: 'E-mail', newPassword: 'Nouveau mot de passe', updateProfile: 'Mettre à jour le profil', demoNotice: 'Les comptes démo peuvent uniquement modifier la devise.', profileSubtitle: 'Personnalisez votre compte et l’affichage de vos finances.', newEntry: 'Nouvelle entrée', addTransaction: 'Ajouter une transaction', cashIn: 'Entrée', cashOut: 'Sortie', category: 'Catégorie', personBusiness: 'Personne / entreprise', note: 'Note', saveTransaction: 'Enregistrer la transaction' },
  de: { welcome: 'Willkommen zurück', register: 'Konto erstellen', overview: 'Übersicht', transactions: 'Transaktionen', settings: 'Einstellungen', workspace: 'Arbeitsbereich', profile: 'Profil', save: 'Einstellungen speichern', currency: 'Währung', language: 'Sprache', preferencesSaved: 'Einstellungen gespeichert.', logout: 'Abmelden', yourKhata: 'Dein Khata', fullName: 'Vollständiger Name', username: 'Benutzername', email: 'E-Mail', newPassword: 'Neues Passwort', updateProfile: 'Profil aktualisieren', demoNotice: 'Demokonten können nur die Währung ändern.', profileSubtitle: 'Personalisiere dein Konto und die Geldanzeige.', newEntry: 'Neuer Eintrag', addTransaction: 'Transaktion hinzufügen', cashIn: 'Einnahmen', cashOut: 'Ausgaben', category: 'Kategorie', personBusiness: 'Person / Unternehmen', note: 'Notiz', saveTransaction: 'Transaktion speichern' },
  tr: { welcome: 'Tekrar hoş geldiniz', register: 'Hesap oluştur', overview: 'Genel bakış', transactions: 'İşlemler', settings: 'Ayarlar', workspace: 'Çalışma alanı', profile: 'Profil', save: 'Tercihleri kaydet', currency: 'Para birimi', language: 'Dil', preferencesSaved: 'Tercihler kaydedildi.', logout: 'Çıkış yap', yourKhata: 'Hesabınız', fullName: 'Ad soyad', username: 'Kullanıcı adı', email: 'E-posta', newPassword: 'Yeni şifre', updateProfile: 'Profili güncelle', demoNotice: 'Demo hesaplar yalnızca para birimini güncelleyebilir.', profileSubtitle: 'Hesabınızı ve para görünümünü kişiselleştirin.', newEntry: 'Yeni kayıt', addTransaction: 'İşlem ekle', cashIn: 'Gelir', cashOut: 'Gider', category: 'Kategori', personBusiness: 'Kişi / işletme', note: 'Not', saveTransaction: 'İşlemi kaydet' },
};
export const languageNames = { en: 'English', ur: 'اردو', hi: 'हिन्दी', ar: 'العربية', es: 'Español', fr: 'Français', de: 'Deutsch', tr: 'Türkçe' };
const I18nContext = createContext(null);
export function I18nProvider({ children }) {
  const storedLanguage = localStorage.getItem('khata_language');
  const [language, setLanguageState] = useState(catalogs[storedLanguage] ? storedLanguage : 'en');
  const setLanguage = (nextLanguage) => setLanguageState(catalogs[nextLanguage] ? nextLanguage : 'en');
  const isRtl = ['ur', 'ar'].includes(language);
  useEffect(() => { localStorage.setItem('khata_language', language); document.documentElement.lang = language; document.documentElement.dir = isRtl ? 'rtl' : 'ltr'; }, [language, isRtl]);
  const value = useMemo(() => ({ language, setLanguage, isRtl, t: (key) => catalogs[language]?.[key] || catalogs.en[key] || key }), [language, isRtl]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export const useI18n = () => useContext(I18nContext);
