import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { khataApi } from '../api/client';
import { useAuth } from '../context/AuthContext';
import TransactionModal from '../components/TransactionModal';
import TransactionRow from '../components/TransactionRow';
import { formatAmount, formatShortDate, getApiError } from '../utils/format';
import { useToast } from '../context/ToastContext';
import { CategoryChart, IncomeOutcomeChart, TrendChart } from '../components/AnalyticsCharts';

export default function Dashboard() {
  const { user } = useAuth(); const { toast, confirm } = useToast(); const [summary, setSummary] = useState(null); const [transactions, setTransactions] = useState([]); const [analytics, setAnalytics] = useState(null); const [period, setPeriod] = useState('month'); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const [data, list] = await Promise.all([khataApi.getAnalytics(user.userId, period), khataApi.getTransactionsByPeriod(user.userId, period)]); setAnalytics(data.data); setSummary(data.data.summary); setTransactions(list.data); } catch (err) { setError(getApiError(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [user.userId, period]);
  const add = async (payload) => { setSaving(true); try { const { data } = await khataApi.createTransaction(payload); setTransactions((items) => [data, ...items]); setSummary((current) => ({ totalCashIn: Number(current.totalCashIn) + (payload.type === 'GOT' ? payload.amount : 0), totalCashOut: Number(current.totalCashOut) + (payload.type === 'GAVE' ? payload.amount : 0), netBalance: Number(current.netBalance) + (payload.type === 'GOT' ? payload.amount : -payload.amount) })); setModal(false); toast('Transaction added successfully.'); } catch (err) { const message = getApiError(err); toast(message, 'error'); throw new Error(message); } finally { setSaving(false); } };
  const deleteItem = async (transaction) => { if (!await confirm('Delete transaction?', `Remove the transaction with ${transaction.partyName}? This cannot be undone.`)) return; try { await khataApi.deleteTransaction(user.userId, transaction.transactionId); setTransactions((items) => items.filter((item) => item.transactionId !== transaction.transactionId)); await load(); toast('Transaction deleted.'); } catch (err) { const message = getApiError(err); setError(message); toast(message, 'error'); } };
  const latest = transactions.slice(0, 5);
  return <>{error && <div className="page-alert form-error">{error}<button onClick={() => setError('')}><i className="bi bi-x" /></button></div>}<section className="welcome-row"><div><p className="eyebrow">{new Intl.DateTimeFormat('en-IN', { weekday: 'long' }).format(new Date())}, {formatShortDate(new Date())}</p><h2>Good morning, {user.fullName.split(' ')[0]} <span className="wave">✦</span></h2><p className="muted">Here’s how your money is looking.</p></div><button className="button-primary" onClick={() => setModal(true)}><i className="bi bi-plus-lg" /> Add transaction</button></section>
    <div className="summary-grid"><SummaryCard label="Cash in" value={summary?.totalCashIn} icon="bi-arrow-down-left" tone="green" loading={loading} period={period} /><SummaryCard label="Cash out" value={summary?.totalCashOut} icon="bi-arrow-up-right" tone="orange" loading={loading} period={period} /><SummaryCard label="Net balance" value={summary?.netBalance} icon="bi-wallet2" tone="dark" loading={loading} period={period} /></div>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Your activity</p><h3>Recent transactions</h3></div><Link to="/transactions" className="text-link">View all <i className="bi bi-arrow-up-right" /></Link></div>{loading ? <div className="empty-state"><span className="spinner-border spinner-border-sm" /> Loading your activity...</div> : latest.length ? latest.map((transaction) => <TransactionRow key={transaction.transactionId} transaction={transaction} onDelete={deleteItem} />) : <EmptyState onAdd={() => setModal(true)} />}</section>
    <section className="analytics-grid"><div className="panel chart-panel chart-wide"><div className="panel-heading"><div><p className="eyebrow">Trend</p><h3>Income vs outcome</h3></div><select className="period-select" value={period} onChange={(event) => setPeriod(event.target.value)} aria-label="Analytics period"><option value="month">This month</option><option value="3-month">Last 3 months</option><option value="6-month">Last 6 months</option><option value="year">This year</option></select></div>{loading ? <div className="chart-placeholder" /> : <TrendChart data={analytics?.trend || []} />}</div><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Categories</p><h3>Where it goes</h3></div></div>{loading ? <div className="chart-placeholder" /> : <CategoryChart data={analytics?.categories || []} />}</div><div className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Monthly view</p><h3>Cash flow</h3></div></div>{loading ? <div className="chart-placeholder" /> : <IncomeOutcomeChart data={analytics?.trend || []} />}</div><div className="panel insight-card"><p className="eyebrow">Smart insight</p><h3>Spending coach</h3><p>{analytics?.insight || 'Add transactions to unlock personalized insights.'}</p></div></section>
    {modal && <TransactionModal onClose={() => setModal(false)} onSubmit={add} submitting={saving} />}
  </>;
}
function SummaryCard({ label, value, icon, tone, loading, period }) {
  const { user } = useAuth();
  const periodLabels = { all: 'All time', month: 'This month', '3-month': 'Last 3 months', '6-month': 'Last 6 months', year: 'This year' };
  return <div className={`summary-card ${tone}`}><div className="summary-top"><span>{label}</span><i className={`bi ${icon}`} /></div>{loading ? <div className="skeleton skeleton-number" /> : <strong>{formatAmount(value, user?.currency)}</strong>}<small>{periodLabels[period] || 'Selected period'}</small></div>;
}
function EmptyState({ onAdd }) { return <div className="empty-state"><span className="empty-icon"><i className="bi bi-receipt" /></span><strong>No transactions yet</strong><span>Start by recording a cash in or cash out.</span><button className="text-link" onClick={onAdd}>Add your first one <i className="bi bi-arrow-right" /></button></div>; }
