import { useEffect, useMemo, useState } from 'react';
import { khataApi } from '../api/client';
import { useAuth } from '../context/AuthContext';
import TransactionModal from '../components/TransactionModal';
import TransactionRow from '../components/TransactionRow';
import { getApiError } from '../utils/format';
import { useToast } from '../context/ToastContext';

export default function Transactions() {
  const { user } = useAuth(); const { toast, confirm } = useToast(); const [items, setItems] = useState([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [period, setPeriod] = useState('year'); const [modal, setModal] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { const { data } = await khataApi.getTransactions(user.userId); setItems(data); } catch (err) { setError(getApiError(err)); } };
  useEffect(() => { load(); }, [user.userId]);
  const filtered = useMemo(() => items.filter((item) => (filter === 'ALL' || item.type === filter) && [item.partyName, item.category, item.note].some((part) => part?.toLowerCase().includes(query.toLowerCase()))), [items, query, filter]);
  const add = async (payload) => { try { const { data } = await khataApi.createTransaction(payload); setItems((current) => [data, ...current]); setModal(false); toast('Transaction added successfully.'); } catch (err) { const message = getApiError(err); toast(message, 'error'); throw new Error(message); } };
  const remove = async (item) => { if (!await confirm('Delete transaction?', `Remove the transaction with ${item.partyName}? This cannot be undone.`)) return; try { await khataApi.deleteTransaction(user.userId, item.transactionId); setItems((current) => current.filter((entry) => entry.transactionId !== item.transactionId)); toast('Transaction deleted.'); } catch (err) { const message = getApiError(err); setError(message); toast(message, 'error'); } };
  const exportFile = async (format) => { try { const response = await khataApi.exportTransactions(user.userId, format, period); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `khata-transactions.${format === 'pdf' ? 'pdf' : 'xlsx'}`; link.click(); URL.revokeObjectURL(url); } catch (err) { toast(getApiError(err), 'error'); } };
  return <>{error && <div className="page-alert form-error">{error}</div>}<section className="welcome-row"><div><p className="eyebrow">Money trail</p><h2>All transactions</h2><p className="muted">Every give and get, in one place.</p></div><button className="button-primary" onClick={() => setModal(true)}><i className="bi bi-plus-lg" /> Add transaction</button></section><section className="panel"><div className="transaction-toolbar"><div className="search-box"><i className="bi bi-search" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search transactions" aria-label="Search transactions" /></div><select className="period-select" value={period} onChange={(event) => setPeriod(event.target.value)} aria-label="Export period"><option value="month">This month</option><option value="3-month">Last 3 months</option><option value="6-month">Last 6 months</option><option value="year">This year</option></select><button className="export-button" onClick={() => exportFile('pdf')} aria-label="Export PDF"><i className="bi bi-file-earmark-pdf" /> PDF</button><button className="export-button" onClick={() => exportFile('excel')} aria-label="Export Excel"><i className="bi bi-file-earmark-spreadsheet" /> Excel</button><div className="filter-tabs"><button className={filter === 'ALL' ? 'active' : ''} onClick={() => setFilter('ALL')}>All</button><button className={filter === 'GOT' ? 'active' : ''} onClick={() => setFilter('GOT')}>Cash in</button><button className={filter === 'GAVE' ? 'active' : ''} onClick={() => setFilter('GAVE')}>Cash out</button></div></div>{filtered.length ? filtered.map((item) => <TransactionRow key={item.transactionId} transaction={item} onDelete={remove} />) : <div className="empty-state"><span className="empty-icon"><i className="bi bi-search" /></span><strong>No matches found</strong><span>Try a different search or filter.</span></div>}</section>{modal && <TransactionModal onClose={() => setModal(false)} onSubmit={add} />}</>;
}
